using Karna.Core.Domain.Enums;

namespace Karna.Core.Application.Mapping
{
	internal static class EgyptLocationMappingExtensions
	{
		private static readonly Dictionary<EgyptLocation, string> DisplayNames = new()
		{
			[EgyptLocation.NewCairo] = "New Cairo",
			[EgyptLocation.FifthSettlement] = "Fifth Settlement (Tagamoa)",
			[EgyptLocation.ElRehab] = "El Rehab",
			[EgyptLocation.Madinaty] = "Madinaty",
			[EgyptLocation.MostakbalCity] = "Mostakbal City",
			[EgyptLocation.ElShorouk] = "El Shorouk",
			[EgyptLocation.Katameya] = "Katameya",
			[EgyptLocation.SixthOfOctober] = "6th of October",
			[EgyptLocation.SheikhZayed] = "Sheikh Zayed",
			[EgyptLocation.NasrCity] = "Nasr City",
			[EgyptLocation.Heliopolis] = "Heliopolis (Masr El Gedida)",
			[EgyptLocation.Sheraton] = "Sheraton",
			[EgyptLocation.ElKorba] = "El Korba",
			[EgyptLocation.Maadi] = "Maadi",
			[EgyptLocation.Basatin] = "Basatin",
			[EgyptLocation.Tora] = "Tora",
			[EgyptLocation.Alexandria] = "Alexandria",
			[EgyptLocation.ElAgamy] = "El Agamy",
			[EgyptLocation.Smouha] = "Smouha",
			[EgyptLocation.SidiGaber] = "Sidi Gaber",
			[EgyptLocation.Stanley] = "Stanley",
			[EgyptLocation.Loran] = "Loran",
			[EgyptLocation.Gleem] = "Gleem",
			[EgyptLocation.SidiBeshr] = "Sidi Beshr",
			[EgyptLocation.Asafra] = "Asafra",
			[EgyptLocation.Miami] = "Miami",
			[EgyptLocation.BorgElArab] = "Borg El Arab",
			[EgyptLocation.Amreya] = "Amreya",
			[EgyptLocation.Cairo] = "Cairo",
			[EgyptLocation.Mokattam] = "Mokattam",
			[EgyptLocation.Helwan] = "Helwan",
			[EgyptLocation.DowntownCairo] = "Downtown Cairo",
			[EgyptLocation.Shubra] = "Shubra",
			[EgyptLocation.ElNozha] = "El Nozha",
			[EgyptLocation.BadrCity] = "Badr City",
			[EgyptLocation.ObourCity] = "Obour City",
			[EgyptLocation.ElSalamCity] = "El Salam City",
			[EgyptLocation.AinShams] = "Ain Shams",
			[EgyptLocation.ElMatareya] = "El Matareya",
			[EgyptLocation.ElMarg] = "El Marg",
			[EgyptLocation.RodElFarag] = "Rod El Farag",
			[EgyptLocation.HadayekElKobba] = "Hadayek El Kobba",
			[EgyptLocation.Abdeen] = "Abdeen",
			[EgyptLocation.GesrElSuez] = "Gesr El Suez",
			[EgyptLocation.Giza] = "Giza",
			[EgyptLocation.ElHaram] = "El Haram",
			[EgyptLocation.Faisal] = "Faisal",
			[EgyptLocation.Dokki] = "Dokki",
			[EgyptLocation.Imbaba] = "Imbaba",
			[EgyptLocation.Mohandessin] = "Mohandessin",
			[EgyptLocation.Marioteya] = "Marioteya",
			[EgyptLocation.HadayekElAhram] = "Hadayek El Ahram",
			[EgyptLocation.HadayekOctober] = "Hadayek October",
			[EgyptLocation.Ramses] = "Ramses",
			[EgyptLocation.Qalyubia] = "Qalyubia",
			[EgyptLocation.Banha] = "Banha",
			[EgyptLocation.ElKhanka] = "El Khanka",
			[EgyptLocation.ElQanater] = "El Qanater",
			[EgyptLocation.ShubraElKheima] = "Shubra El Kheima",
			[EgyptLocation.Sharqia] = "Sharqia",
			[EgyptLocation.Zagazig] = "Zagazig",
			[EgyptLocation.Bilbeis] = "Bilbeis",
			[EgyptLocation.TenthOfRamadan] = "10th of Ramadan",
			[EgyptLocation.Dakahlia] = "Dakahlia",
			[EgyptLocation.ElMansoura] = "El Mansoura",
			[EgyptLocation.Talkha] = "Talkha",
			[EgyptLocation.MitGhamr] = "Mit Ghamr",
			[EgyptLocation.Gharbia] = "Gharbia",
			[EgyptLocation.Tanta] = "Tanta",
			[EgyptLocation.ElMahallaElKubra] = "El Mahalla El Kubra",
			[EgyptLocation.KafrElZayat] = "Kafr El Zayat",
			[EgyptLocation.Monufia] = "Monufia",
			[EgyptLocation.ShebinElKom] = "Shebin El Kom",
			[EgyptLocation.SadatCity] = "Sadat City",
			[EgyptLocation.Ashmoun] = "Ashmoun",
			[EgyptLocation.Quesna] = "Quesna",
			[EgyptLocation.BerketElSaba] = "Berket El Saba",
			[EgyptLocation.KafrElSheikh] = "Kafr El Sheikh",
			[EgyptLocation.Beheira] = "Beheira",
			[EgyptLocation.Damanhour] = "Damanhour",
			[EgyptLocation.KafrElDawwar] = "Kafr El Dawwar",
			[EgyptLocation.Rashid] = "Rashid",
			[EgyptLocation.Shubrakhit] = "Shubrakhit",
			[EgyptLocation.Damietta] = "Damietta",
			[EgyptLocation.RasElBar] = "Ras El Bar",
			[EgyptLocation.Ismailia] = "Ismailia",
			[EgyptLocation.PortSaid] = "Port Said",
			[EgyptLocation.Suez] = "Suez",
			[EgyptLocation.AinSokhna] = "Ain Sokhna",
			[EgyptLocation.Fayoum] = "Fayoum",
			[EgyptLocation.BeniSuef] = "Beni Suef",
			[EgyptLocation.Minya] = "Minya",
			[EgyptLocation.Asyut] = "Asyut",
			[EgyptLocation.Sohag] = "Sohag",
			[EgyptLocation.Qena] = "Qena",
			[EgyptLocation.Luxor] = "Luxor",
			[EgyptLocation.Aswan] = "Aswan",
			[EgyptLocation.KomOmbo] = "Kom Ombo",
			[EgyptLocation.NewValley] = "New Valley",
			[EgyptLocation.RedSea] = "Red Sea",
			[EgyptLocation.Hurghada] = "Hurghada",
			[EgyptLocation.ElGouna] = "El Gouna",
			[EgyptLocation.MarsaMatrouh] = "Marsa Matrouh",
			[EgyptLocation.NorthCoast] = "North Coast (Sahel)",
			[EgyptLocation.ElAlamein] = "El Alamein",
			[EgyptLocation.Sinai] = "Sinai",
			[EgyptLocation.SharmElSheikh] = "Sharm El Sheikh",
			[EgyptLocation.Dahab] = "Dahab",
			[EgyptLocation.Nuweiba] = "Nuweiba",
			[EgyptLocation.RasSudr] = "Ras Sudr",
			[EgyptLocation.OtherUnknown] = "Other/Unknown"
		};

		public static string ToDisplayString(this EgyptLocation location)
			=> DisplayNames.TryGetValue(location, out var name) ? name : location.ToString();
	}
}
