//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karna.Core.Application.Localization.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karna.Core.Application.Localization.Resources.Messages.ApiResponseMessages", typeof(ApiResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing is already in your favorites..
        /// </summary>
        public static string AlreadyInFavorites {
            get {
                return ResourceManager.GetString("AlreadyInFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition checklist updated successfully..
        /// </summary>
        public static string ChecklistUpdated {
            get {
                return ResourceManager.GetString("ChecklistUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition checklist category activated successfully..
        /// </summary>
        public static string ConditionChecklistCategoryActivated {
            get {
                return ResourceManager.GetString("ConditionChecklistCategoryActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition checklist category created successfully..
        /// </summary>
        public static string ConditionChecklistCategoryCreated {
            get {
                return ResourceManager.GetString("ConditionChecklistCategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition checklist category deactivated successfully..
        /// </summary>
        public static string ConditionChecklistCategoryDeactivated {
            get {
                return ResourceManager.GetString("ConditionChecklistCategoryDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition checklist category deleted successfully..
        /// </summary>
        public static string ConditionChecklistCategoryDeleted {
            get {
                return ResourceManager.GetString("ConditionChecklistCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition checklist category updated successfully..
        /// </summary>
        public static string ConditionChecklistCategoryUpdated {
            get {
                return ResourceManager.GetString("ConditionChecklistCategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition defect activated successfully..
        /// </summary>
        public static string ConditionDefectActivated {
            get {
                return ResourceManager.GetString("ConditionDefectActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition defect created successfully..
        /// </summary>
        public static string ConditionDefectCreated {
            get {
                return ResourceManager.GetString("ConditionDefectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition defect deactivated successfully..
        /// </summary>
        public static string ConditionDefectDeactivated {
            get {
                return ResourceManager.GetString("ConditionDefectDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition defect deleted successfully..
        /// </summary>
        public static string ConditionDefectDeleted {
            get {
                return ResourceManager.GetString("ConditionDefectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition defect updated successfully..
        /// </summary>
        public static string ConditionDefectUpdated {
            get {
                return ResourceManager.GetString("ConditionDefectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to favorites..
        /// </summary>
        public static string FavoriteAdded {
            get {
                return ResourceManager.GetString("FavoriteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from favorites..
        /// </summary>
        public static string FavoriteRemoved {
            get {
                return ResourceManager.GetString("FavoriteRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing approved successfully..
        /// </summary>
        public static string ListingApproved {
            get {
                return ResourceManager.GetString("ListingApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing archived successfully..
        /// </summary>
        public static string ListingArchived {
            get {
                return ResourceManager.GetString("ListingArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing created successfully..
        /// </summary>
        public static string ListingCreated {
            get {
                return ResourceManager.GetString("ListingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing deleted successfully..
        /// </summary>
        public static string ListingDeleted {
            get {
                return ResourceManager.GetString("ListingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted by seller.
        /// </summary>
        public static string ListingDeletedReason {
            get {
                return ResourceManager.GetString("ListingDeletedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing marked as sold successfully..
        /// </summary>
        public static string ListingMarkedAsSold {
            get {
                return ResourceManager.GetString("ListingMarkedAsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing rejected..
        /// </summary>
        public static string ListingRejected {
            get {
                return ResourceManager.GetString("ListingRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing submitted for review successfully..
        /// </summary>
        public static string ListingSubmitted {
            get {
                return ResourceManager.GetString("ListingSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing updated successfully..
        /// </summary>
        public static string ListingUpdated {
            get {
                return ResourceManager.GetString("ListingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make activated successfully..
        /// </summary>
        public static string MakeActivated {
            get {
                return ResourceManager.GetString("MakeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make created successfully..
        /// </summary>
        public static string MakeCreated {
            get {
                return ResourceManager.GetString("MakeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make deactivated successfully..
        /// </summary>
        public static string MakeDeactivated {
            get {
                return ResourceManager.GetString("MakeDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make deleted successfully..
        /// </summary>
        public static string MakeDeleted {
            get {
                return ResourceManager.GetString("MakeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make updated successfully..
        /// </summary>
        public static string MakeUpdated {
            get {
                return ResourceManager.GetString("MakeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model activated successfully..
        /// </summary>
        public static string ModelActivated {
            get {
                return ResourceManager.GetString("ModelActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model created successfully.
        /// </summary>
        public static string ModelCreated {
            get {
                return ResourceManager.GetString("ModelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model deactivated successfully..
        /// </summary>
        public static string ModelDeactivated {
            get {
                return ResourceManager.GetString("ModelDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model deleted successfully.
        /// </summary>
        public static string ModelDeleted {
            get {
                return ResourceManager.GetString("ModelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model updated successfully.
        /// </summary>
        public static string ModelUpdated {
            get {
                return ResourceManager.GetString("ModelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos uploaded successfully.
        /// </summary>
        public static string PhotosUploaded {
            get {
                return ResourceManager.GetString("PhotosUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price generated successfully..
        /// </summary>
        public static string PriceGenerated {
            get {
                return ResourceManager.GetString("PriceGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing price set successfully..
        /// </summary>
        public static string PriceSet {
            get {
                return ResourceManager.GetString("PriceSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful..
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
    }
}
