//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karna.Core.Application.Localization.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karna.Core.Application.Localization.Resources.Messages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is inactive..
        /// </summary>
        internal static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked. Please try again later..
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition checklist category not found..
        /// </summary>
        internal static string ConditionChecklistCategoryNotFound {
            get {
                return ResourceManager.GetString("ConditionChecklistCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more selected condition items are inactive..
        /// </summary>
        internal static string ConditionDefectInactive {
            get {
                return ResourceManager.GetString("ConditionDefectInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more selected condition items were not found..
        /// </summary>
        internal static string ConditionDefectItemsNotFound {
            get {
                return ResourceManager.GetString("ConditionDefectItemsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition defect not found..
        /// </summary>
        internal static string ConditionDefectNotFound {
            get {
                return ResourceManager.GetString("ConditionDefectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use..
        /// </summary>
        internal static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform this action..
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error occurred..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing does not belong to you.
        /// </summary>
        internal static string InvalidListingOwner {
            get {
                return ResourceManager.GetString("InvalidListingOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid price greater than zero..
        /// </summary>
        internal static string InvalidListingPrice {
            get {
                return ResourceManager.GetString("InvalidListingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing cannot be deleted.
        /// </summary>
        internal static string ListingCannotBeDeleted {
            get {
                return ResourceManager.GetString("ListingCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required vehicle details before generating price..
        /// </summary>
        internal static string ListingDataIncompleteForPricing {
            get {
                return ResourceManager.GetString("ListingDataIncompleteForPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing is no longer available..
        /// </summary>
        internal static string ListingDeleted {
            get {
                return ResourceManager.GetString("ListingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required listing details before submitting..
        /// </summary>
        internal static string ListingIncompleteData {
            get {
                return ResourceManager.GetString("ListingIncompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 3 photos are required to submit a listing..
        /// </summary>
        internal static string ListingInsufficientPhotos {
            get {
                return ResourceManager.GetString("ListingInsufficientPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a condition checklist before submitting..
        /// </summary>
        internal static string ListingMissingChecklist {
            get {
                return ResourceManager.GetString("ListingMissingChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please generate ML pricing before submitting..
        /// </summary>
        internal static string ListingMissingPricing {
            get {
                return ResourceManager.GetString("ListingMissingPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing is no longer available..
        /// </summary>
        internal static string ListingNotAvailable {
            get {
                return ResourceManager.GetString("ListingNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing not found..
        /// </summary>
        internal static string ListingNotFound {
            get {
                return ResourceManager.GetString("ListingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing must be in Active state..
        /// </summary>
        internal static string ListingNotInActiveState {
            get {
                return ResourceManager.GetString("ListingNotInActiveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing must be in Draft state to modify the checklist..
        /// </summary>
        internal static string ListingNotInDraftState {
            get {
                return ResourceManager.GetString("ListingNotInDraftState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing must be in Pending state..
        /// </summary>
        internal static string ListingNotInPendingState {
            get {
                return ResourceManager.GetString("ListingNotInPendingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing must be in Draft or Pending state to generate a price..
        /// </summary>
        internal static string ListingNotInValidStateForPricing {
            get {
                return ResourceManager.GetString("ListingNotInValidStateForPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing cannot be updated in its current state..
        /// </summary>
        internal static string ListingNotInValidStateForUpdate {
            get {
                return ResourceManager.GetString("ListingNotInValidStateForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to modify this listing..
        /// </summary>
        internal static string ListingNotOwnedByUser {
            get {
                return ResourceManager.GetString("ListingNotOwnedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make not found..
        /// </summary>
        internal static string MakeNotFound {
            get {
                return ResourceManager.GetString("MakeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listing&apos;s make or model could not be found..
        /// </summary>
        internal static string MakeOrModelNotFound {
            get {
                return ResourceManager.GetString("MakeOrModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pricing service is temporarily unavailable. Please try again later..
        /// </summary>
        internal static string MLServiceUnavailable {
            get {
                return ResourceManager.GetString("MLServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model not found.
        /// </summary>
        internal static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please generate a price suggestion first before accepting..
        /// </summary>
        internal static string NoPriceGeneratedYet {
            get {
                return ResourceManager.GetString("NoPriceGeneratedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload photos.
        /// </summary>
        internal static string PhotoUploadFailed {
            get {
                return ResourceManager.GetString("PhotoUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed. Please try again..
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource..
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email already exists..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
