//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karna.Core.Application.Localization.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karna.Core.Application.Localization.Resources.Messages.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A condition checklist category with this name already exists..
        /// </summary>
        internal static string ConditionChecklistCategoryNameAlreadyExists {
            get {
                return ResourceManager.GetString("ConditionChecklistCategoryNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A condition defect with this name already exists for this category..
        /// </summary>
        internal static string ConditionDefectNameAlreadyExists {
            get {
                return ResourceManager.GetString("ConditionDefectNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use..
        /// </summary>
        internal static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine size must be a positive number..
        /// </summary>
        internal static string EngineSizeMustBePositive {
            get {
                return ResourceManager.GetString("EngineSizeMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid fuel type..
        /// </summary>
        internal static string InvalidFuelType {
            get {
                return ResourceManager.GetString("InvalidFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only image files are allowed.
        /// </summary>
        internal static string InvalidPhotoType {
            get {
                return ResourceManager.GetString("InvalidPhotoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid price..
        /// </summary>
        internal static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid transmission type..
        /// </summary>
        internal static string InvalidTransmission {
            get {
                return ResourceManager.GetString("InvalidTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid year..
        /// </summary>
        internal static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Id is required.
        /// </summary>
        internal static string ListingIdRequired {
            get {
                return ResourceManager.GetString("ListingIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing cannot be modified at this stage.
        /// </summary>
        internal static string ListingNotEditable {
            get {
                return ResourceManager.GetString("ListingNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A make with this name already exists..
        /// </summary>
        internal static string MakeNameAlreadyExists {
            get {
                return ResourceManager.GetString("MakeNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of {0} characters exceeded..
        /// </summary>
        internal static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload up to 10 photos only.
        /// </summary>
        internal static string MaxPhotosExceeded {
            get {
                return ResourceManager.GetString("MaxPhotosExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage must be a positive number..
        /// </summary>
        internal static string MileageMustBePositive {
            get {
                return ResourceManager.GetString("MileageMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is {0} characters..
        /// </summary>
        internal static string MinLengthExceeded {
            get {
                return ResourceManager.GetString("MinLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected model does not belong to the selected make..
        /// </summary>
        internal static string ModelDoesNotBelongToMake {
            get {
                return ResourceManager.GetString("ModelDoesNotBelongToMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name already exists for this make..
        /// </summary>
        internal static string ModelNameAlreadyExists {
            get {
                return ResourceManager.GetString("ModelNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit..
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character..
        /// </summary>
        internal static string PasswordRequiresSpecial {
            get {
                return ResourceManager.GetString("PasswordRequiresSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo cannot be empty.
        /// </summary>
        internal static string PhotoEmpty {
            get {
                return ResourceManager.GetString("PhotoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos already uploaded for this listing.
        /// </summary>
        internal static string PhotosAlreadyExist {
            get {
                return ResourceManager.GetString("PhotosAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must upload between 3 and 10 photos.
        /// </summary>
        internal static string PhotosCountInvalid {
            get {
                return ResourceManager.GetString("PhotosCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo size must not exceed 5 MB.
        /// </summary>
        internal static string PhotoSizeExceeded {
            get {
                return ResourceManager.GetString("PhotoSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos are required.
        /// </summary>
        internal static string PhotosRequired {
            get {
                return ResourceManager.GetString("PhotosRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPhotoType.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken..
        /// </summary>
        internal static string UsernameAlreadyTaken {
            get {
                return ResourceManager.GetString("UsernameAlreadyTaken", resourceCulture);
            }
        }
    }
}
